# Generated by Django 3.1.7 on 2021-05-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnjrCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craddate', models.DateField()),
                ('text', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='')),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TodayCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrddate', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=64)),
                ('text_author', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='')),
                ('dzcount', models.IntegerField()),
                ('collectcount', models.IntegerField()),
                ('commentcount', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
        ),
    ]
