# Generated by Django 3.1.7 on 2021-05-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todayCard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnjrcard',
            name='picture',
            field=models.ImageField(upload_to='media/qnjrCard/img/'),
        ),
        migrations.AlterField(
            model_name='todaycard',
            name='picture',
            field=models.ImageField(upload_to='media/todayCard/img/'),
        ),
    ]
