# Generated by Django 3.1.7 on 2021-05-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todayCard', '0003_auto_20210514_2330'),
        ('accounts', '0004_auto_20210514_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctext', models.CharField(max_length=50)),
                ('tcid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todayCard.todaycard')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
