# Generated by Django 3.1.7 on 2021-05-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todayCard', '0002_auto_20210513_1857'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='media/user/avator/')),
                ('collectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectid', to='todayCard.todaycard')),
                ('contributeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributeid', to='todayCard.todaycard')),
            ],
        ),
        migrations.CreateModel(
            name='password',
            fields=[
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('md5', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
