# Generated by Django 3.1.7 on 2021-05-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210513_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='uid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user'),
        ),
    ]
